---
- name: Ensure nginx is installed (Debian)
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: true
