---
all:
  children:
    webservers:
      hosts:
        ansible-node1.baachridge.io:
        ansible-node2.baachridge.io:
        ansible-node3.baachridge.io:
        ansible-node4.baachridge.io:
        ansible-node5.baachridge.io:
